name: Multiple Group Approval

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened]

jobs:
  check_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check approvals
        id: check_approvals
        run: |

          # Get the JSON containing information about the pull request
          pr_info=$(jq '.pull_request.reviews[]' $GITHUB_EVENT_PATH)
          echo "Pull Requsest Information: $pr_info"

         

      

          
          


        
       
