name: Multiple Group Approval

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  check_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check approvals
        id: check_approvals
        run: |

          # Get the JSON containing information about the approvals
          approvals_json=$(jq '.reviews[] | {state: .state, author_association: .author_association, author_teams: .author_teams[].name}' $GITHUB_EVENT_PATH)
          echo "Approvals JSON: $approvals_json"


        
       
