name: Multiple Group Approval

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  check_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check approvals
        id: check_approvals
        run: |

          # Get the JSON containing information about the pull request
          pr_info=$(jq '.pull_request' $GITHUB_EVENT_PATH)
          echo "Pull Request Information: $pr_info"


          review_info=$(jq '.reviews[]' $GITHUB_EVENT_PATH)

          echo " $review_info"
        
       
